users:
  - userName: 'rexi'
files:
  - name: todo.txt
    text: |-
      * Bei Kollegen vorstellen
      * JoJo finden

      Erledigt:
      * System aufsetzen
      * Benutzer anlegen
      * Software installieren
mails:
  - timestamp: 2076-09-25T08:30:35
    from: 'Tech Support <TechSupport@BPC-Systems.com>'
    to: 'Björn Nisse <nisse@BPC-Systems.com>'
    subject: 'Willkommen bei BPC Systems'
    text: |-
      Sehr geehrter Herr Nisse,

      herzlich willkommen bei BPC Systems. Wir haben ihr System erfolgreich eingerichtet.
      Weitere Dokumente können Sie über den Host "mainframe" einsehen

      Mit freundlichen Grüßen,

      BPC Systems Tech Support