files:
  - name: dance.vid
    youTube: https://www.youtube.com/embed/dQw4w9WgXcQ
  - name: "stellar-monarch.txt"
    text: "Stellar Monarch: Passenger Shuttle. The Stellar Monarch has an ellipsoid hull with aerodynamic wings. It is equipped with 140 passenger seats and a landing shuttle."
  - name: bd.vid
    youTube: https://www.youtube.com/embed/N47_Gz6RJfY
  - name: jojo.ai
    sequence: "data/jojo.yml"
    passwords:
      - "14052021" # Hochzeit
      - "27052022" # Hochzeitsfeier
      - "08052021" # JGA Björn
      - "08111991" # Geburtstag Björn
      - "11022020" # Verlobungstag
      - "13011990" # Geburtstag Johanna
mails:
  - timestamp: 2077-04-25T07:11:42
    from: "Chief Executive Officer <CEO@BPC-Systems.com>"
    to: "Alexis Patriot <patriot@BPC-Systems.com>"
    subject: "Quartalsbericht Q1 2077"
    text: |-
      Solider Start ins neue Jahr – insbesondere in Wachstumssegmenten Nutrition & Care und Resource Efficiency.

      Ausblick für das Geschäftsjahr 2077 angepasst an aktuelles Umfeld: bereinigtes EBITDA zwischen 17 und 21 Milliarden ED erwartet.

      Strategie-Update: Neue Divisionsstruktur und Finanzziele treiben strategische Weiterentwicklung voran

      Deutlich positiver Free Cash Flow im ersten Quartal
users:
  - userName: patriot
    passwords:
      - "favorJUSTtrust51"
