defaultHost: "localhost"
defaultUser: "rexi"
startupText: |-
  ██████╗ ██████╗  ██████╗    ███████╗██╗   ██╗███████╗████████╗███████╗███╗   ███╗███████╗
  ██╔══██╗██╔══██╗██╔════╝    ██╔════╝╚██╗ ██╔╝██╔════╝╚══██╔══╝██╔════╝████╗ ████║██╔════╝
  ██████╔╝██████╔╝██║         ███████╗ ╚████╔╝ ███████╗   ██║   █████╗  ██╔████╔██║███████╗
  ██╔══██╗██╔═══╝ ██║         ╚════██║  ╚██╔╝  ╚════██║   ██║   ██╔══╝  ██║╚██╔╝██║╚════██║
  ██████╔╝██║     ╚██████╗    ███████║   ██║   ███████║   ██║   ███████╗██║ ╚═╝ ██║███████║
  ╚═════╝ ╚═╝      ╚═════╝    ╚══════╝   ╚═╝   ╚══════╝   ╚═╝   ╚══════╝╚═╝     ╚═╝╚══════╝

  Willkommen bei BPC Systems

  Verwenden Sie den 'help' Befehl, um einen Hilfetext anzuzeigen
helpText: |-
  help - zeigt diesen Hilfetext an
  files.list - listet alle Dateien auf dem derzeitigen Host auf
  files.open {file: "[filename]"} - öffnet die angegebene Datei
  mails.list - listet alle Mails auf dem derzeitigen Host auf
  mails.open {id: 1} - öffnet die Mail mit der angegebenen ID
  connect {host: "[hostname]"} - stellt die Verbindung zu dem angegebnen Host her
   
  Verwenden Sie ArrowUp und ArrowDown um durch die Historie der zuvor verwendeten Kommandos zu navigieren

  Daten werden per Parameter {} an Kommandos übergeben
  Parameter bestehen aus einem Key-Value-Paar
  Der Key ist der Name des Parameters, zB: 'name:', 'file:'
  Ein Value ist der Inhalt des Parameters, zB: 1, "hilfe.txt"

  Mehrere Key-Value-Paare werden per Komma getrennt, zB: {user: "username", password: "password1234"}
  Der Schlüssel steht links vom Wert, getrennt durch einen Doppelpunkt  {file: "hilfe.txt"}
  Kommando und Parameter sind durch ein (oder mehrere) Leerzeichen getrennt.
  Innerhalb der Klammern {} können beliebig viele Leerzeichen (außerhalb der Anführungszeichen) zur besseren Lesbarkeit verwendet werden.