defaultHost: 'localhost'
defaultUser: 'rexi'
startupText: |-
  ██████╗ ██████╗  ██████╗    ███████╗██╗   ██╗███████╗████████╗███████╗███╗   ███╗███████╗
  ██╔══██╗██╔══██╗██╔════╝    ██╔════╝╚██╗ ██╔╝██╔════╝╚══██╔══╝██╔════╝████╗ ████║██╔════╝
  ██████╔╝██████╔╝██║         ███████╗ ╚████╔╝ ███████╗   ██║   █████╗  ██╔████╔██║███████╗
  ██╔══██╗██╔═══╝ ██║         ╚════██║  ╚██╔╝  ╚════██║   ██║   ██╔══╝  ██║╚██╔╝██║╚════██║
  ██████╔╝██║     ╚██████╗    ███████║   ██║   ███████║   ██║   ███████╗██║ ╚═╝ ██║███████║
  ╚═════╝ ╚═╝      ╚═════╝    ╚══════╝   ╚═╝   ╚══════╝   ╚═╝   ╚══════╝╚═╝     ╚═╝╚══════╝
  
  Willkommen bei BPC Systems

  Verwenden sie den 'help' Befehl, um einen Hilfetext azuzeigen