defaultHost: "localhost"
defaultUser: "rexi"
startupText: |-
  ██████╗ ██████╗  ██████╗    ███████╗██╗   ██╗███████╗████████╗███████╗███╗   ███╗███████╗
  ██╔══██╗██╔══██╗██╔════╝    ██╔════╝╚██╗ ██╔╝██╔════╝╚══██╔══╝██╔════╝████╗ ████║██╔════╝
  ██████╔╝██████╔╝██║         ███████╗ ╚████╔╝ ███████╗   ██║   █████╗  ██╔████╔██║███████╗
  ██╔══██╗██╔═══╝ ██║         ╚════██║  ╚██╔╝  ╚════██║   ██║   ██╔══╝  ██║╚██╔╝██║╚════██║
  ██████╔╝██║     ╚██████╗    ███████║   ██║   ███████║   ██║   ███████╗██║ ╚═╝ ██║███████║
  ╚═════╝ ╚═╝      ╚═════╝    ╚══════╝   ╚═╝   ╚══════╝   ╚═╝   ╚══════╝╚═╝     ╚═╝╚══════╝

  Willkommen bei BPC Systems

  Verwenden Sie den 'help' Befehl, um einen Hilfetext azuzeigen
  Lesen Sie die Hilfedatei mit dem Befehl 'files.open {file: "help.txt"}'
